name: MapRatingSystem
main: dev.dementisimus.mrs.MapRatingSystem
author: dementisimus
version: ${project.version}
website: dementisimus.dev
softdepend: [ CoreAPI, ProtocolLib, CoreAPIDependencies ]
api-version: 1.17

commands:
  maprating:
  mr:
