name: MapRatingSystem
main: dev.dementisimus.mrs.MapRatingSystemPlugin
author: dementisimus
version: ${project.version}
website: dementisimus.dev
softdepend: [ CoreAPI, ProtocolLib, CoreAPI-Dependencies ]
api-version: 1.17

commands:
  maprating:
  mr:
