name: MapRatingSystem
main: dev.dementisimus.mrs.MapRatingSystem
author: dementisimus
version: 1.2.0
website: dementisimus.dev
softdepend: [ CoreAPI, ProtocolLib ]
api-version: 1.17

commands:
  maprating:
  mr:
