name: build
on: [ push, workflow_dispatch ]

env: 
  name: MapRatingSystem
  id: mrs

jobs:
  build:  
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
          
      - name: setup-jdk-16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ secrets.CACHE_KEY }}

      - name: evaluate project info
        run: |
          echo "version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: set jar & pom env vars
        run: |
          echo "jar=${{ env.name }}-${{ env.version }}.jar" >> $GITHUB_ENV
          echo "pom=${{ env.name }}-${{ env.version }}.pom" >> $GITHUB_ENV

      - name: build
        run: mvn -U clean package javadoc:javadoc --file pom.xml
            
      - name: pre-deploy
        run: |
          mkdir ./artifacts
          mkdir ./javadocs
          cp ./target/${{ env.jar }} ./artifacts/${{ env.jar }}
          cp ./pom.xml ./artifacts/${{ env.pom }}
          cp -R ./target/site/apidocs/. ./javadocs
            
      - name: deploy release artifacts
        if: endsWith(github.ref, '/main')
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./artifacts
          remote: /home/repo-deployment/repository/repositories/release/dev/dementisimus/${{ env.id }}/${{ env.name }}/${{ env.version }}/
          concurrency: 5
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}

      - name: deploy development artifacts
        if: endsWith(github.ref, '/develop')
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./artifacts
          remote: /home/repo-deployment/repository/repositories/development/dev/dementisimus/${{ env.id }}/${{ env.name }}/${{ env.version }}/
          concurrency: 5
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
            
      - name: deploy release javadocs
        if: endsWith(github.ref, '/main')
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./javadocs
          remote: /var/www/dementisimus.dev/html/docs/release/${{ env.name }}/${{ env.version }}/
          concurrency: 5
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}

      - name: deploy development javadocs
        if: endsWith(github.ref, '/develop')
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: ./javadocs
          remote: /var/www/dementisimus.dev/html/docs/development/${{ env.name }}/${{ env.version }}/
          concurrency: 5
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}